services:
  - type: web
    name: price-tracking-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn price_tracking_project.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString

  - type: worker
    name: scraper-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A price_tracking_project worker --loglevel=info
