# Generated by Django 5.1.6 on 2026-01-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackedproduct_remove_productprice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='is_summary',
            field=models.BooleanField(default=False),
        ),
    ]
